package br.com.estoque.model;

public enum DescricaoAnimal {
	VACA_12M, VACA_12A24M, VACA_24A36M, VACA_CONSERVA, VACA_TF, VACA_MACHUCADA, 
	BOI_12M, BOI_24A24M, BOI_24A36M, BOI_TF, BOI_MACHUCADO, BOI_CONSERVA, TOURO_12M, 
	TOURO_12A24M, TOURO_24A36M, TOURO_MACHUCADO, TOURO_TF, TOURO_CONSERVA;

}
